version: '3.7'

services:
  web:
    image: webdevops/php-apache:alpine-php7
    restart: always
    ports:
      - "4500:80"
    volumes:  
      - /data/php/:/app

    networks:
      - minha-rede

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "senha123"
      MYSQL_DATABASE:  "testedb"
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql-C:/var/lib/mysql

    networks:
      -  minha-rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "senha123"
    ports:
      - "8080:80"
    volumes:
      - /data/php/admin/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge

